import type { AgentId, AgentSummary } from './types'

export const ADMITTED_AGENTS: AgentSummary[] = [
  {
    id: 'yixuan',
    name: 'Yixuan',
    attribute: 'Auric Ink',
    specialty: 'Rupture',
    focusEligible: true,
    rank: 'S',
    faction: 'Yunkui Summit',
  },
  {
    id: 'dialyn',
    name: 'Dialyn',
    attribute: 'Physical',
    specialty: 'Stun',
    focusEligible: false,
    rank: 'S',
  },
  {
    id: 'lucia',
    name: 'Lucia',
    attribute: 'Ether',
    specialty: 'Support',
    focusEligible: false,
    rank: 'S',
  },
  {
    id: 'anbySoldier0',
    name: 'Anby: Soldier 0',
    attribute: 'Electric',
    specialty: 'Attack',
    focusEligible: true,
    rank: 'S',
  },
  {
    id: 'trigger',
    name: 'Trigger',
    attribute: 'Electric',
    specialty: 'Stun',
    focusEligible: false,
    rank: 'S',
  },
  {
    id: 'astraYao',
    name: 'Astra Yao',
    attribute: 'Ether',
    specialty: 'Support',
    focusEligible: false,
    rank: 'S',
  },
  {
    id: 'seed',
    name: 'Seed',
    attribute: 'Electric',
    specialty: 'Attack',
    focusEligible: true,
    rank: 'S',
  },
  {
    id: 'cissia',
    name: 'Cissia',
    attribute: 'Electric',
    specialty: 'Attack',
    focusEligible: false,
    rank: 'S',
  },
  {
    id: 'evelyn',
    name: 'Evelyn',
    attribute: 'Fire',
    specialty: 'Attack',
    focusEligible: true,
    rank: 'S',
  },
  {
    id: 'corin',
    name: 'Corin',
    attribute: 'Physical',
    specialty: 'Attack',
    focusEligible: true,
    rank: 'A',
    faction: 'Victoria Housekeeping Co.',
  },
  {
    id: 'lycaon',
    name: 'Lycaon',
    attribute: 'Ice',
    specialty: 'Stun',
    focusEligible: false,
    rank: 'S',
    faction: 'Victoria Housekeeping Co.',
  },
  {
    id: 'yidhari',
    name: 'Yidhari',
    attribute: 'Ice',
    specialty: 'Rupture',
    focusEligible: true,
    rank: 'S',
  },
  {
    id: 'manato',
    name: 'Manato',
    attribute: 'Fire',
    specialty: 'Rupture',
    focusEligible: true,
    rank: 'A',
  },
  {
    id: 'hugo',
    name: 'Hugo',
    attribute: 'Ice',
    specialty: 'Attack',
    focusEligible: true,
    rank: 'S',
  },
  {
    id: 'juFufu',
    name: 'Ju Fufu',
    attribute: 'Fire',
    specialty: 'Stun',
    focusEligible: false,
    rank: 'S',
    faction: 'Yunkui Summit',
  },
  {
    id: 'panYinhu',
    name: 'Pan Yinhu',
    attribute: 'Physical',
    specialty: 'Defense',
    focusEligible: false,
    rank: 'A',
    faction: 'Yunkui Summit',
  },
  {
    id: 'banyue',
    name: 'Banyue',
    attribute: 'Fire',
    specialty: 'Rupture',
    focusEligible: true,
    rank: 'S',
  },
  {
    id: 'starlightBilly',
    name: 'Starlight Billy',
    attribute: 'Physical',
    specialty: 'Rupture',
    focusEligible: true,
    rank: 'S',
  },
  {
    id: 'ellen', name: 'Ellen', attribute: 'Ice', specialty: 'Attack',
    focusEligible: true, rank: 'S', faction: 'Victoria Housekeeping Co.',
  },
  {
    id: 'soukaku', name: 'Soukaku', attribute: 'Ice', specialty: 'Support',
    focusEligible: false, rank: 'A', faction: 'Section 6',
  },
]

export const defaultMindscapeFor = (agentId: AgentId): 0 | 6 =>
  ADMITTED_AGENTS.find(({ id }) => id === agentId)?.rank === 'A' ? 6 : 0

export const isFocusEligible = (agentId: AgentId): boolean =>
  ADMITTED_AGENTS.find((agent) => agent.id === agentId)?.focusEligible ?? false

export const DEFAULT_APPLIED_AGENT_IDS: [AgentId, AgentId, AgentId] = [
  'yixuan',
  'dialyn',
  'lucia',
]
