export const VERTICAL_VALUES = {
  fixedDisc: {
    hp: 2200,
    atk: 316,
    def: 184,
  },
  rupture: {
    currentAtkToSheer: 0.3,
    currentHpToSheer: 0.1,
  },
  yixuan: {
    hp: 8373,
    atk: 872,
    critRate: 19.4,
    critDmg: 50,
    coreActionDmgBonus: 60,
    additionalCritDmg: 40,
    additionalExDmgBonus: 30,
    mindscapeCritRate: 10,
    mindscapeEtherResIgnore: 15,
    mindscapeStunExtension: 3,
    mindscapeActionDmgPerStack: 30,
    mindscapeMeditationSheerDmg: 20,
  },
  yidhari: {
    hp: 8497,
    atk: 859,
    critRate: 19.4,
    critDmg: 50,
    lowHpDmg: 100,
    additionalCritDmg: 50,
    mindscapeIceResIgnore: 20,
    mindscapeCritDmg: 40,
    mindscapeMaxHp: 5,
    mindscapeSheerDmg: 25,
  },
  manato: {
    hp: 7725,
    atk: 755,
    critRate: 5,
    critDmg: 50,
    coreHp: 18,
    moltenCritRate: 10,
    moltenFireDmg: 20,
    coreActionCritDmg: 50,
    mindscapeActionFireDmg: 20,
    mindscapeFireResIgnore: 8,
    mindscapeHp: 8,
    mindscapeAssistFireDmg: 15,
  },
  hugo: {
    atk: 919,
    critRate: 19.4,
    critDmg: 50,
    coreCritRate: 12,
    coreCritDmg: 25,
    coreAtkOneStun: 300,
    coreAtkTwoStun: 900,
    coreTotalizeMultiplier: 3400,
    coreDazeReturn: 25,
    exNonStunnedDaze: 20,
    additionalChainDmg: 15,
    additionalTotalizeDmg: 40,
    mindscapeCritRate: 12,
    mindscapeCritDmg: 30,
    mindscapeTotalizeDefIgnore: 15,
    mindscapeIceResIgnore: 12,
    mindscapeTotalizeDmg: 60,
    mindscapeExTotalizeMultiplier: 1000,
  },
  juFufu: {
    atk: 765,
    critRate: 19.4,
    critDmg: 50,
    impact: 118,
    baseEnergyRegen: 1.2,
    coreCritDmg: 20,
    coreCritDmgThreshold: 2800,
    coreCritDmgCapAtk: 3400,
    coreCritDmgPer100Atk: 5,
    coreCritDmgBonusCap: 30,
    coreChainDmg: 20,
    coreUltimateDmg: 40,
    coreImpact: 50,
    kingCritThreshold: 50,
    mindscapeCritRate: 12,
    mindscapeStunMultiplier: 35,
    mindscapeSquadCritDmg: 22,
    mindscapeSelfCritDmg: 35,
    mindscapeChainDmg: 30,
    mindscapePopcornMultiplier: 480,
  },
  panYinhu: {
    atk: 661,
    impact: 94,
    baseEnergyRegen: 1.56,
    coreAtkRatio: 18,
    coreSheerCap: 540,
    additionalDmg: 20,
    mindscapeAdditionalDmg: 10,
    mindscapeCoreAtkRatio: 24,
    mindscapeCoreSheerCap: 720,
    mindscapeEnergyRestore: 4,
  },
  banyue: {
    hp: 8497,
    atk: 859,
    critRate: 19.4,
    critDmg: 50,
    coreSheerForce: 300,
    coreFireDmg: 36,
    coreCritDmg: 36,
    additionalFireDmgPerStack: 5,
    additionalStacks: 3,
    mindscapeFireResReduction: 10,
    mindscapeActionSheerDmg: 10,
    mindscapeStunExtension: 2,
    mindscapeCoreCritDmg: 15,
    mindscapeCoreFireDmg: 15,
    mindscapeActionDmg: 30,
    mindscapeVidyarajaPerStack: 8,
    mindscapeCrushingPeaksMultiplier: 600,
  },
  starlightBilly: {
    hp: 8497,
    atk: 859,
    critRate: 19.4,
    critDmg: 50,
    coreCritDmg: 90,
    additionalDmgPerStack: 20,
    additionalStacks: 2,
    mindscapePhysicalResIgnore: 18,
    mindscapeActionDmg: 50,
    mindscapeCoolWheelieCritDmg: 50,
    mindscapeCoreCritDmgPerStack: 8,
    mindscapeCoreCritDmgStacks: 2,
    mindscapeSheerDmg: 18,
    mindscapeAddedPhysicalDmgPerStack: 100,
    mindscapeConsumedStacks: 2,
  },
  dialyn: {
    critRate: 19.4,
    critDmg: 50,
    impact: 110,
    baseEnergyRegen: 1.2,
    critThreshold: 50,
    impactPerCrit: 2,
    impactBonusCap: 100,
    mindscapeDmg: 15,
    mindscapeStunMultiplier: 20,
    mindscapeResIgnore: 15,
  },
  lucia: {
    hp: 8477,
    critDmg: 50,
    baseEnergyRegen: 1.3,
    darkbreakerBase: 12,
    darkbreakerPer200Hp: { base: 7.4, m3: 7.8, m5: 8.2 },
    darkbreakerCap: { base: 900, m3: 948, m5: 996 },
    darkbreakerHpCap: 24000,
    mindscapeSheerDmg: 15,
    mindscapeResIgnore: 18,
  },
  party: {
    dialynDmg: 40,
    dialynStunMultiplier: 30,
    dialynStunExtension: 2,
    luciaCoreDmg: 20,
    luciaCritDmg: 30,
    wellspringHp: 5,
  },
  anbySoldier0: { hp: 7673, atk: 929, critRate: 19.4, critDmg: 50, impact: 93 },
  trigger: {
    hp: 7923,
    atk: 750,
    critRate: 5,
    critDmg: 50,
    impact: 131,
    baseEnergyRegen: 1.2,
  },
  astraYao: { hp: 8609, atk: 715, baseEnergyRegen: 1.56 },
  seed: {
    atk: 929,
    critRate: 5,
    critDmg: 78.8,
    coreStatus: {
      atk: 1000,
      critDmg: 30,
    } satisfies Record<'atk' | 'critDmg', number>,
  },
  cissia: { atk: 938, critRate: 5, critDmg: 50, baseEnergyRegen: 1.56 },
  evelyn: {
    atk: 929,
    critRate: 19.4,
    critDmg: 50,
    coreCritRate: 25,
    additionalChainUltimateDmg: 30,
    additionalCritThreshold: 80,
    additionalMultiplier: 1.25,
    mindscapeDefIgnore: 12,
    mindscapeAtk: 15,
    mindscapeCritDmg: 40,
  },
  corin: {
    atk: 807,
    critRate: 5,
    critDmg: 78.8,
    baseEnergyRegen: 1.2,
    coreChainsawDmg: 37.5,
    additionalStunnedDmg: 35,
    mindscapeDmg: 12,
    mindscapePhysicalResReduction: 10,
  },
  lycaon: {
    impact: 137,
    critRate: 5,
    baseEnergyRegen: 1.2,
    coreChargedDaze: 80,
    coreIceResReduction: 25,
    coreOtherAttributeDmg: 30,
    glacialWaltzDaze: 48,
    potentialImpact: 15,
    additionalStunMultiplier: 35,
    mindscapeExDaze: 12,
    mindscapeFullChargeDaze: 10,
    kingCritThreshold: 50,
  },
  ellen: {
    atk: 938, critRate: 19.4, critDmg: 50, baseEnergyRegen: 1.2,
    coreCritDmg: 100, additionalIceDmg: 30, potentialCritDmg: 48,
    potentialIceResIgnore: 10, mindscapeCritRate: 12, mindscapeExCritDmg: 60,
    mindscapePenRatio: 20, mindscapeChargedDmg: 250,
  },
  soukaku: {
    atk: 665, critRate: 5, critDmg: 50, baseEnergyRegen: 1.56,
    coreAtkRatio: 40, coreAtkCap: 2500, coreOutputCap: 1000,
    additionalIceDmg: 20, mindscapeIceResReduction: 10,
  },
  soldier11: {
    atk: 888, critRate: 19.4, critDmg: 50, baseEnergyRegen: 1.2,
    coreActionFireDmg: 70, additionalFireDmg: 10, additionalStunnedFireDmg: 22.5,
    potentialCritDmg: 48, mindscapeActionDmg: 36, mindscapeFireResIgnore: 25,
  },
  lighter: {
    atk: 797, critRate: 5, critDmg: 50, impact: 137, baseEnergyRegen: 1.2,
    coreCombatImpact: 20, coreFireIceResReduction: 15, coreStunExtension: 3,
    elationBaseImpact: 170, elationStepImpact: 10, elationFireIceDmgPerStep: 5,
    elationFireIceDmgAtTwentyStacks: 25, elationFireIceDmgCap: 75,
    kingCritThreshold: 50, mindscapeStunExtension: 5, mindscapeFireIceResReduction: 10,
    mindscapeStunMultiplier: 25, mindscapeElationMultiplier: 1.2,
  },
  lucy: {
    atk: 658, critRate: 5, critDmg: 50, baseEnergyRegen: 1.56,
    coreAtkRatioByMindscapeTier: [22.6, 24.2, 25.8], coreAtkBaseByMindscapeTier: [88, 96, 104],
    coreAtkOutputCap: 600, mindscapeSquadCritDmg: 10,
  },
  zhuYuan: {
    atk: 919, critRate: 5, critDmg: 78.8,
    coreEnhancedDmg: 40, coreStunnedDmg: 40, additionalCritRate: 30,
    mindscapeEnhancedDmg: 50, mindscapeEtherResIgnore: 25,
  },
  nicole: {
    atk: 649, baseEnergyRegen: 1.56,
    coreDefReduction: 40, additionalEtherDmg: 25, mindscapeSquadCritRate: 15,
  },
  orphie: {
    atk: 929, critRate: 5, critDmg: 50, baseEnergyRegen: 1.56,
    coreCritRate: 25, coreAftershockDmg: 85,
    coreSquadAtkBase: 280, coreSquadAtkStep: 20,
    coreEnergyThreshold: 1.6, coreEnergyStep: 0.1, coreSquadAtkCap: 700,
    additionalAftershockDefIgnore: 25,
    mindscapeFireResIgnore: 15, mindscapeSquadDmg: 20,
    mindscapeAtk: 20, mindscapeActionDmg: 40,
  },
  pulchra: {
    atk: 665, critRate: 5, critDmg: 50, impact: 136, baseEnergyRegen: 1.2,
    coreDaze: 30, additionalDmg: 30,
    mindscapeCritRate: 10, mindscapeAtk: 10, kingCritThreshold: 50,
  },
  harumasa: {
    atk: 915, critRate: 19.4, critDmg: 50, baseEnergyRegen: 1.2,
    coreCritRate: 25, coreCritDmg: 72,
    potentialAtk: 12, potentialElectricResIgnore: 15,
    additionalDmg: 40,
    mindscapeDashDmg: 50, mindscapeElectricResIgnore: 15,
  },
  qingyi: {
    atk: 758, critRate: 5, critDmg: 50, impact: 136, baseEnergyRegen: 1.2,
    flashDmg: 25, flashDaze: 12.5,
    coreStunMultiplier: 80, coreChainDmg: 60,
    additionalBasicDaze: 20,
    additionalImpactThreshold: 120, additionalImpactCap: 220,
    additionalAtkPerImpact: 6, additionalAtkCap: 600,
    mindscapeDefReduction: 15, mindscapeCritRate: 20,
    mindscapeStunMultiplier: 108, mindscapeDaze: 15,
    mindscapeEnchantedCritDmg: 100, mindscapeResReduction: 20,
    kingCritThreshold: 50,
  },
  nekomata: {
    atk: 910, critRate: 19.4, critDmg: 50, baseEnergyRegen: 1.2,
    coreDmg: 60, potentialCritDmg: 60, additionalActionDmg: 70,
    mindscapePhysicalResIgnore: 16, mindscapeEnergyRegen: 0.3,
    mindscapeCritRate: 14, mindscapeCritDmg: 54,
  },
  billy: {
    atk: 787, critRate: 19.4, critDmg: 50, baseEnergyRegen: 1.2,
    coreActionDmg: 50, additionalUltimateDmg: 100,
    mindscapeDodgeDmg: 25, mindscapeExCritRate: 32,
    mindscapeDmg: 30,
  },
  ben: {
    atk: 867, def: 724, critRate: 5, critDmg: 50, impact: 95, baseEnergyRegen: 1.56,
    coreDefToAtk: 80,
    additionalCritRate: 16,
    mindscapeCounterDefDamage: 300, mindscapeCounterDmg: 30, mindscapeDaze: 20,
  },
  koleda: {
    atk: 735, critRate: 5, critDmg: 50, impact: 134, baseEnergyRegen: 1.2,
    coreDaze: 60, additionalChainDmg: 70,
    mindscapeDaze: 15, mindscapeDmgPerCharge: 18,
    mindscapeDmgMax: 36, mindscapeExplosionAtk: 360,
    kingCritThreshold: 50,
  },
  anby: {
    atk: 658, critRate: 5, critDmg: 50, impact: 136, baseEnergyRegen: 1.2,
    coreActionDaze: 64,
    mindscapeThunderboltStunnedDmg: 30,
    mindscapeExNonStunnedDaze: 10,
    mindscapeBasicDashDmg: 45,
    kingCritThreshold: 50,
  },
  caesar: {
    atk: 711, critRate: 5, critDmg: 50, impact: 123,
    additionalDmgBonus: 25,
    coreFocusAtk: 1000, mindscapeFocusAtk: 1500,
    coreImpactByTier: [20, 22, 24],
    ultimateDazeByTier: [100, 110, 120],
    mindscapeResReduction: 15,
    mindscapeCritRate: 30, mindscapeCritDmg: 60,
    mindscapeActionCritRate: 100, mindscapeActionDmg: 50,
    mindscapePrimaryTargetFollowup: 50,
  },
  yeShunguang: {
    atk: 938,
    critRate: 19.4,
    critDmg: 50,
    unityCritRate: 30,
    unityDmg: 25,
    veilVulnerabilityCap: 110,
    mindscapeUnityDmg: 10,
    mindscapeDefIgnore: 20,
    mindscapeActionDefIgnore: 40,
    mindscapeVeilVulnerabilityCap: 200,
  },
  zhao: {
    hp: 9117,
    atk: 765,
    critRate: 5,
    critDmg: 50,
    baseEnergyRegen: 1.2,
    coreHp: 18,
    coreCritRatePer1000Hp: 1.4,
    mindscapeCoreCritRateMultiplier: 1.25,
    wellspringHp: 5,
    wellspringAtk: 1000,
    additionalDmg: 10,
    additionalHpThreshold: 15000,
    additionalHpStep: 400,
    additionalDmgPerStep: 1,
    additionalHpCap: 27000,
    additionalDmgCap: 40,
    mindscapeResIgnore: 15,
    mindscapeSelfAtk: 20,
    mindscapeOtherAtk: 15,
    mindscapeActionCritDmg: 40,
    finalVerdictMaxHp: 120,
    mindscapeFinalVerdictMaxHp: 168,
  },
  grace: {
    atk: 825,
    anomalyProficiency: 116,
    anomalyMastery: 151,
    baseEnergyRegen: 1.2,
    coreAnomalyBuildup: 130,
    additionalShockDmgPerStack: 18,
    additionalShockDmgStacks: 2,
    potentialElectricDmg: 30,
    mindscapeElectricResReduction: 8.5,
    mindscapeElectricBuildupResReduction: 8.5,
    mindscapeGrenadeDmgMultiplier: 2,
  },
} as const

export const SEED_SETUP_PASSIVE_LINES = [
  'Vanguard +2 Energy when Seed deals damage as the active character, once per 1s',
] as const

const SOURCE_CATEGORY_LABELS = {
  corePassive: 'Core Passive',
  additionalAbility: 'Additional Ability',
  exSpecialAttack: 'EX Special Attack',
  mindscape: 'Mindscape',
} as const

export const SOURCE_LABELS = {
  slot4: 'Drive Disc \u00B7 Slot 4',
  slot5: 'Drive Disc \u00B7 Slot 5',
  slot6: 'Drive Disc \u00B7 Slot 6',
  yixuanCore: SOURCE_CATEGORY_LABELS.corePassive,
  yixuanAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  yidhariCore: SOURCE_CATEGORY_LABELS.corePassive,
  yidhariAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  manatoCore: SOURCE_CATEGORY_LABELS.corePassive,
  hugoCore: SOURCE_CATEGORY_LABELS.corePassive,
  hugoAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  juFufuCore: SOURCE_CATEGORY_LABELS.corePassive,
  panYinhuCore: SOURCE_CATEGORY_LABELS.corePassive,
  panYinhuAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  banyueCore: SOURCE_CATEGORY_LABELS.corePassive,
  banyueAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  starlightBillyCore: SOURCE_CATEGORY_LABELS.corePassive,
  starlightBillyAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  dialynCore: SOURCE_CATEGORY_LABELS.corePassive,
  dialynAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  luciaCore: SOURCE_CATEGORY_LABELS.corePassive,
  luciaAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  luciaSheer: SOURCE_CATEGORY_LABELS.exSpecialAttack,
  anbySoldier0Core: SOURCE_CATEGORY_LABELS.corePassive,
  anbySoldier0Ability: SOURCE_CATEGORY_LABELS.additionalAbility,
  triggerCore: SOURCE_CATEGORY_LABELS.corePassive,
  triggerAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  astraCore: SOURCE_CATEGORY_LABELS.corePassive,
  astraCadenza: 'Special Attack',
  seedCore: SOURCE_CATEGORY_LABELS.corePassive,
  seedAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  cissiaCore: SOURCE_CATEGORY_LABELS.corePassive,
  cissiaAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  cissiaBasic: 'Basic Attack',
  evelynCore: SOURCE_CATEGORY_LABELS.corePassive,
  evelynAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  corinCore: SOURCE_CATEGORY_LABELS.corePassive,
  corinAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  lycaonCore: SOURCE_CATEGORY_LABELS.corePassive,
  lycaonAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  lycaonPotential: 'Potential Awakening',
  ellenCore: SOURCE_CATEGORY_LABELS.corePassive,
  ellenAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  ellenPotential: 'Potential Awakening',
  soukakuCore: SOURCE_CATEGORY_LABELS.corePassive,
  soukakuAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  soldier11Core: SOURCE_CATEGORY_LABELS.corePassive,
  soldier11Ability: SOURCE_CATEGORY_LABELS.additionalAbility,
  soldier11Potential: 'Potential Awakening',
  lighterCore: SOURCE_CATEGORY_LABELS.corePassive,
  lighterAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  lucyCore: SOURCE_CATEGORY_LABELS.corePassive,
  lucyAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  zhuYuanCore: SOURCE_CATEGORY_LABELS.corePassive,
  zhuYuanAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  nicoleCore: SOURCE_CATEGORY_LABELS.corePassive,
  nicoleAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  orphieCore: SOURCE_CATEGORY_LABELS.corePassive,
  orphieAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  pulchraCore: SOURCE_CATEGORY_LABELS.corePassive,
  pulchraAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  harumasaCore: SOURCE_CATEGORY_LABELS.corePassive,
  harumasaAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  harumasaPotential: 'Potential Awakening',
  qingyiCore: SOURCE_CATEGORY_LABELS.corePassive,
  qingyiAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  nekomataCore: SOURCE_CATEGORY_LABELS.corePassive,
  nekomataAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  nekomataPotential: 'Potential Awakening',
  billyCore: SOURCE_CATEGORY_LABELS.corePassive,
  billyAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  benCore: SOURCE_CATEGORY_LABELS.corePassive,
  benAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  koledaCore: SOURCE_CATEGORY_LABELS.corePassive,
  koledaAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  anbyCore: SOURCE_CATEGORY_LABELS.corePassive,
  caesarCore: SOURCE_CATEGORY_LABELS.corePassive,
  caesarAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  yeShunguangCore: SOURCE_CATEGORY_LABELS.corePassive,
  zhaoCore: SOURCE_CATEGORY_LABELS.corePassive,
  zhaoAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  zhaoBasic: 'Basic Attack',
  graceCore: SOURCE_CATEGORY_LABELS.corePassive,
  graceAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  gracePotential: 'Potential Awakening',
  mindscape: SOURCE_CATEGORY_LABELS.mindscape,
} as const
