export const VERTICAL_VALUES = {
  fixedDisc: {
    hp: 2200,
    atk: 316,
  },
  rupture: {
    currentAtkToSheer: 0.3,
    currentHpToSheer: 0.1,
  },
  yixuan: {
    hp: 8373,
    atk: 872,
    critRate: 19.4,
    critDmg: 50,
    coreActionDmgBonus: 60,
    additionalCritDmg: 40,
    additionalExDmgBonus: 30,
    mindscapeCritRate: 10,
    mindscapeEtherResIgnore: 15,
    mindscapeStunExtension: 3,
    mindscapeActionDmgPerStack: 30,
    mindscapeMeditationSheerDmg: 20,
  },
  yidhari: {
    hp: 8497,
    atk: 859,
    critRate: 19.4,
    critDmg: 50,
    lowHpDmg: 100,
    additionalCritDmg: 50,
    mindscapeIceResIgnore: 20,
    mindscapeCritDmg: 40,
    mindscapeMaxHp: 5,
    mindscapeSheerDmg: 25,
  },
  manato: {
    hp: 7725,
    atk: 755,
    critRate: 5,
    critDmg: 50,
    coreHp: 18,
    moltenCritRate: 10,
    moltenFireDmg: 20,
    coreActionCritDmg: 50,
    mindscapeActionFireDmg: 20,
    mindscapeFireResIgnore: 8,
    mindscapeHp: 8,
    mindscapeAssistFireDmg: 15,
  },
  hugo: {
    atk: 919,
    critRate: 19.4,
    critDmg: 50,
    coreCritRate: 12,
    coreCritDmg: 25,
    coreAtkOneStun: 300,
    coreAtkTwoStun: 900,
    coreTotalizeMultiplier: 3400,
    coreDazeReturn: 25,
    exNonStunnedDaze: 20,
    additionalChainDmg: 15,
    additionalTotalizeDmg: 40,
    mindscapeCritRate: 12,
    mindscapeCritDmg: 30,
    mindscapeTotalizeDefIgnore: 15,
    mindscapeIceResIgnore: 12,
    mindscapeTotalizeDmg: 60,
    mindscapeExTotalizeMultiplier: 1000,
  },
  juFufu: {
    atk: 765,
    critRate: 19.4,
    critDmg: 50,
    impact: 118,
    baseEnergyRegen: 1.2,
    coreCritDmg: 20,
    coreCritDmgThreshold: 2800,
    coreCritDmgCapAtk: 3400,
    coreCritDmgPer100Atk: 5,
    coreCritDmgBonusCap: 30,
    coreChainDmg: 20,
    coreUltimateDmg: 40,
    coreImpact: 50,
    kingCritThreshold: 50,
    mindscapeCritRate: 12,
    mindscapeStunMultiplier: 35,
    mindscapeSquadCritDmg: 22,
    mindscapeSelfCritDmg: 35,
    mindscapeChainDmg: 30,
    mindscapePopcornMultiplier: 480,
  },
  panYinhu: {
    atk: 661,
    impact: 94,
    baseEnergyRegen: 1.56,
    coreAtkRatio: 18,
    coreSheerCap: 540,
    additionalDmg: 20,
    mindscapeAdditionalDmg: 10,
    mindscapeCoreAtkRatio: 24,
    mindscapeCoreSheerCap: 720,
    mindscapeEnergyRestore: 4,
  },
  banyue: {
    hp: 8497,
    atk: 859,
    critRate: 19.4,
    critDmg: 50,
    coreSheerForce: 300,
    coreFireDmg: 36,
    coreCritDmg: 36,
    additionalFireDmgPerStack: 5,
    additionalStacks: 3,
    mindscapeFireResReduction: 10,
    mindscapeActionSheerDmg: 10,
    mindscapeStunExtension: 2,
    mindscapeCoreCritDmg: 15,
    mindscapeCoreFireDmg: 15,
    mindscapeActionDmg: 30,
    mindscapeVidyarajaPerStack: 8,
    mindscapeCrushingPeaksMultiplier: 600,
  },
  dialyn: {
    critRate: 19.4,
    critDmg: 50,
    impact: 110,
    baseEnergyRegen: 1.2,
    critThreshold: 50,
    impactPerCrit: 2,
    impactBonusCap: 100,
    mindscapeDmg: 15,
    mindscapeStunMultiplier: 20,
    mindscapeResIgnore: 15,
  },
  lucia: {
    hp: 8477,
    critDmg: 50,
    baseEnergyRegen: 1.3,
    darkbreakerBase: 12,
    darkbreakerPer200Hp: { base: 7.4, m3: 7.8, m5: 8.2 },
    darkbreakerCap: { base: 900, m3: 948, m5: 996 },
    darkbreakerHpCap: 24000,
    mindscapeSheerDmg: 15,
    mindscapeResIgnore: 18,
  },
  party: {
    dialynDmg: 40,
    dialynStunMultiplier: 30,
    dialynStunExtension: 2,
    luciaCoreDmg: 20,
    luciaCritDmg: 30,
    wellspringHp: 5,
  },
  anbySoldier0: { hp: 7673, atk: 929, critRate: 19.4, critDmg: 50, impact: 93 },
  trigger: {
    hp: 7923,
    atk: 750,
    critRate: 5,
    critDmg: 50,
    impact: 131,
    baseEnergyRegen: 1.2,
  },
  astraYao: { hp: 8609, atk: 715, baseEnergyRegen: 1.56 },
  seed: {
    atk: 929,
    critRate: 5,
    critDmg: 78.8,
    coreStatus: {
      atk: 1000,
      critDmg: 30,
    } satisfies Record<'atk' | 'critDmg', number>,
  },
  cissia: { atk: 938, critRate: 5, critDmg: 50, baseEnergyRegen: 1.56 },
  evelyn: {
    atk: 929,
    critRate: 19.4,
    critDmg: 50,
    coreCritRate: 25,
    additionalChainUltimateDmg: 30,
    additionalCritThreshold: 80,
    additionalMultiplier: 1.25,
    mindscapeDefIgnore: 12,
    mindscapeAtk: 15,
    mindscapeCritDmg: 40,
  },
  corin: {
    atk: 807,
    critRate: 5,
    critDmg: 78.8,
    baseEnergyRegen: 1.2,
    coreChainsawDmg: 37.5,
    additionalStunnedDmg: 35,
    mindscapeDmg: 12,
    mindscapePhysicalResReduction: 10,
  },
  lycaon: {
    impact: 137,
    critRate: 5,
    baseEnergyRegen: 1.2,
    coreChargedDaze: 80,
    coreIceResReduction: 25,
    coreOtherAttributeDmg: 30,
    glacialWaltzDaze: 48,
    potentialImpact: 15,
    additionalStunMultiplier: 35,
    mindscapeExDaze: 12,
    mindscapeFullChargeDaze: 10,
    kingCritThreshold: 50,
  },
} as const

export const SEED_SETUP_PASSIVE_LINES = [
  'Vanguard +2 Energy when Seed deals damage as the active character, once per 1s',
] as const

const SOURCE_CATEGORY_LABELS = {
  corePassive: 'Core Passive',
  additionalAbility: 'Additional Ability',
  exSpecialAttack: 'EX Special Attack',
  mindscape: 'Mindscape',
} as const

export const SOURCE_LABELS = {
  slot4: 'Drive Disc \u00B7 Slot 4',
  slot5: 'Drive Disc \u00B7 Slot 5',
  slot6: 'Drive Disc \u00B7 Slot 6',
  yixuanCore: SOURCE_CATEGORY_LABELS.corePassive,
  yixuanAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  yidhariCore: SOURCE_CATEGORY_LABELS.corePassive,
  yidhariAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  manatoCore: SOURCE_CATEGORY_LABELS.corePassive,
  hugoCore: SOURCE_CATEGORY_LABELS.corePassive,
  hugoAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  juFufuCore: SOURCE_CATEGORY_LABELS.corePassive,
  panYinhuCore: SOURCE_CATEGORY_LABELS.corePassive,
  panYinhuAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  banyueCore: SOURCE_CATEGORY_LABELS.corePassive,
  banyueAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  dialynCore: SOURCE_CATEGORY_LABELS.corePassive,
  dialynAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  luciaCore: SOURCE_CATEGORY_LABELS.corePassive,
  luciaAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  luciaSheer: SOURCE_CATEGORY_LABELS.exSpecialAttack,
  anbyCore: SOURCE_CATEGORY_LABELS.corePassive,
  anbyAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  triggerCore: SOURCE_CATEGORY_LABELS.corePassive,
  triggerAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  astraCore: SOURCE_CATEGORY_LABELS.corePassive,
  astraCadenza: 'Special Attack',
  seedCore: SOURCE_CATEGORY_LABELS.corePassive,
  seedAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  cissiaCore: SOURCE_CATEGORY_LABELS.corePassive,
  cissiaAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  cissiaBasic: 'Basic Attack',
  evelynCore: SOURCE_CATEGORY_LABELS.corePassive,
  evelynAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  corinCore: SOURCE_CATEGORY_LABELS.corePassive,
  corinAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  lycaonCore: SOURCE_CATEGORY_LABELS.corePassive,
  lycaonAbility: SOURCE_CATEGORY_LABELS.additionalAbility,
  lycaonPotential: 'Potential Awakening',
  mindscape: SOURCE_CATEGORY_LABELS.mindscape,
} as const
